<?php
/**
 *  Copyright 2015 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 */

//namespace SwaggerClient;
namespace RC\client;

class APIVersioningApi {

  function __construct($apiClient = null) {
    $this->apiClient = $apiClient;
  }

  /**
   * @var ApiClient
   */
  private $apiClient;

  /**
   * get the API client
   */
  public function getApiClient() {
    return $this->apiClient;
  }

  /**
   * set the API client
   */
  public function setApiClient($apiClient) {
    $this->apiClient = $apiClient;
  }

  
  /**
   * Get API Versions
   *
   * @param `Options` $options Options object
   *
   * @struct Options {
   * }
   *
   * @return \RC\client\models\GetVersionsResponse
   */
   //public function versions() {
   public function versions($options) {

      if (empty($options)) $options = [];

      

      // parse inputs
      $resourcePath = "/";
      $resourcePath = str_replace("{format}", "json", $resourcePath);
      $method = "GET";
      $httpBody = '';
      $queryParams = array();
      $headerParams = array();
      $formParams = array();

      $_header_accept = $this->apiClient->selectHeaderAccept(array('application/json'));
      if (!is_null($_header_accept)) {
        $headerParams['Accept'] = $_header_accept;
      }
      $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType(array('application/json'));

      

      

      

      

      

      // for model (json/xml)
      if (isset($_tempBody)) {
        $httpBody = $_tempBody; // $_tempBody is the method argument, if present
      } else if (count($formParams) > 0) {
        // for HTTP post (form)
        $httpBody = $formParams;
      }

      // authentication setting, if any
      $authSettings = array();

      // make the API Call
      $response = $this->apiClient->callAPI($resourcePath, $method,
                                            $queryParams, $httpBody,
                                            $headerParams, $authSettings);

      if(! $response) {
        return null;
      }

      $responseObject = $this->apiClient->deserialize($response,'GetVersionsResponse');
      return $responseObject;

  }
  
  /**
   * Get Version Info
   *
   * @param `Options` $options Options object
   *
   * @struct Options {
   *     @type string  'api_version'  API version to be requested, for example &#39;v1.0&#39; (required)
   * }
   *
   * @return \RC\client\models\GetVersionResponse
   */
   //public function version($api_version) {
   public function version($options) {

      if (empty($options)) $options = [];

      
      // verify the required parameter 'api_version' is set
      $this->apiClient->validateParameter($options, 'api_version', 'version');
      

      // parse inputs
      $resourcePath = "/{apiVersion}";
      $resourcePath = str_replace("{format}", "json", $resourcePath);
      $method = "GET";
      $httpBody = '';
      $queryParams = array();
      $headerParams = array();
      $formParams = array();

      $_header_accept = $this->apiClient->selectHeaderAccept(array('application/json'));
      if (!is_null($_header_accept)) {
        $headerParams['Accept'] = $_header_accept;
      }
      $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType(array('application/json'));

      

      

      $resourcePath = $this->apiClient->parsePathParam($resourcePath, $options, 'api_version', 'apiVersion');
      

      

      

      // for model (json/xml)
      if (isset($_tempBody)) {
        $httpBody = $_tempBody; // $_tempBody is the method argument, if present
      } else if (count($formParams) > 0) {
        // for HTTP post (form)
        $httpBody = $formParams;
      }

      // authentication setting, if any
      $authSettings = array();

      // make the API Call
      $response = $this->apiClient->callAPI($resourcePath, $method,
                                            $queryParams, $httpBody,
                                            $headerParams, $authSettings);

      if(! $response) {
        return null;
      }

      $responseObject = $this->apiClient->deserialize($response,'GetVersionResponse');
      return $responseObject;

  }
  

}
