<?php
/**
 *  Copyright 2015 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 */

//namespace SwaggerClient;
namespace RC\client;

class CallLogApi {

  function __construct($apiClient = null) {
    $this->apiClient = $apiClient;
  }

  /**
   * @var ApiClient
   */
  private $apiClient;

  /**
   * get the API client
   */
  public function getApiClient() {
    return $this->apiClient;
  }

  /**
   * set the API client
   */
  public function setApiClient($apiClient) {
    $this->apiClient = $apiClient;
  }

  
  /**
   * Get Account Active Calls
   *
   * @param `Options` $options Options object
   *
   * @struct Options {
   *     @type int  'account_id'  Internal identifier of a RingCentral account or tilde (~) to indicate the account logged-in within the current session (required)
   *     @type array[string]  'direction'  The direction for the result records. It is allowed to specify more than one direction. If not specified, both inbound and outbound records are returned. Multiple values are accepted (required)
   *     @type array[string]  'type'  Call type of a record. It is allowed to specify more than one type. If not specified, all call types are returned. Multiple values are accepted (required)
   *     @type int  'page'  Indicates the page number to retrieve. Only positive number values are allowed. Default value is &#39;1&#39;. (required)
   *     @type int  'per_page'  Indicates the page size (number of items). If not specified, the value is &#39;100&#39; by default. (required)
   * }
   *
   * @return \RC\client\models\AccountActiveCallsResponse
   */
   //public function accountActiveCalls($account_id, $direction, $type, $page, $per_page) {
   public function accountActiveCalls($options) {

      if (empty($options)) $options = [];

      
      // verify the required parameter 'account_id' is set
      $this->apiClient->validateParameter($options, 'account_id', 'accountActiveCalls');
      

      // parse inputs
      $resourcePath = "/v1.0/account/{accountId}/active-calls";
      $resourcePath = str_replace("{format}", "json", $resourcePath);
      $method = "GET";
      $httpBody = '';
      $queryParams = array();
      $headerParams = array();
      $formParams = array();

      $_header_accept = $this->apiClient->selectHeaderAccept(array('application/json'));
      if (!is_null($_header_accept)) {
        $headerParams['Accept'] = $_header_accept;
      }
      $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType(array('application/json'));

      $queryParams = $this->apiClient->parseQueryParam($queryParams, $options, 'direction', 'direction');
      $queryParams = $this->apiClient->parseQueryParam($queryParams, $options, 'type', 'type');
      $queryParams = $this->apiClient->parseQueryParam($queryParams, $options, 'page', 'page');
      $queryParams = $this->apiClient->parseQueryParam($queryParams, $options, 'per_page', 'perPage');
      

      

      $resourcePath = $this->apiClient->parsePathParam($resourcePath, $options, 'account_id', 'accountId');
      

      

      

      // for model (json/xml)
      if (isset($_tempBody)) {
        $httpBody = $_tempBody; // $_tempBody is the method argument, if present
      } else if (count($formParams) > 0) {
        // for HTTP post (form)
        $httpBody = $formParams;
      }

      // authentication setting, if any
      $authSettings = array();

      // make the API Call
      $response = $this->apiClient->callAPI($resourcePath, $method,
                                            $queryParams, $httpBody,
                                            $headerParams, $authSettings);

      if(! $response) {
        return null;
      }

      $responseObject = $this->apiClient->deserialize($response,'AccountActiveCallsResponse');
      return $responseObject;

  }
  
  /**
   * Get Active Calls
   *
   * @param `Options` $options Options object
   *
   * @struct Options {
   *     @type int  'account_id'  Internal identifier of a RingCentral account or tilde (~) to indicate the account logged-in within the current session (required)
   *     @type array[string]  'direction'  The direction for the result records. It is allowed to specify more than one direction. If not specified, both inbound and outbound records are returned. Multiple values are accepted (required)
   *     @type array[string]  'type'  Call type of a record. It is allowed to specify more than one type. If not specified, all call types are returned. Multiple values are accepted (required)
   *     @type int  'page'  Indicates the page number to retrieve. Only positive number values are allowed. Default value is &#39;1&#39;. (required)
   *     @type int  'per_page'  Indicates the page size (number of items). If not specified, the value is &#39;100&#39; by default. (required)
   * }
   *
   * @return \RC\client\models\ExtensionActiveCallsResponse
   */
   //public function accountExtensionActiveCalls($account_id, $direction, $type, $page, $per_page) {
   public function accountExtensionActiveCalls($options) {

      if (empty($options)) $options = [];

      
      // verify the required parameter 'account_id' is set
      $this->apiClient->validateParameter($options, 'account_id', 'accountExtensionActiveCalls');
      

      // parse inputs
      $resourcePath = "/v1.0/account/{accountId}/extension/{extensionId}/active-calls";
      $resourcePath = str_replace("{format}", "json", $resourcePath);
      $method = "GET";
      $httpBody = '';
      $queryParams = array();
      $headerParams = array();
      $formParams = array();

      $_header_accept = $this->apiClient->selectHeaderAccept(array('application/json'));
      if (!is_null($_header_accept)) {
        $headerParams['Accept'] = $_header_accept;
      }
      $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType(array('application/json'));

      $queryParams = $this->apiClient->parseQueryParam($queryParams, $options, 'direction', 'direction');
      $queryParams = $this->apiClient->parseQueryParam($queryParams, $options, 'type', 'type');
      $queryParams = $this->apiClient->parseQueryParam($queryParams, $options, 'page', 'page');
      $queryParams = $this->apiClient->parseQueryParam($queryParams, $options, 'per_page', 'perPage');
      

      

      $resourcePath = $this->apiClient->parsePathParam($resourcePath, $options, 'account_id', 'accountId');
      

      

      

      // for model (json/xml)
      if (isset($_tempBody)) {
        $httpBody = $_tempBody; // $_tempBody is the method argument, if present
      } else if (count($formParams) > 0) {
        // for HTTP post (form)
        $httpBody = $formParams;
      }

      // authentication setting, if any
      $authSettings = array();

      // make the API Call
      $response = $this->apiClient->callAPI($resourcePath, $method,
                                            $queryParams, $httpBody,
                                            $headerParams, $authSettings);

      if(! $response) {
        return null;
      }

      $responseObject = $this->apiClient->deserialize($response,'ExtensionActiveCallsResponse');
      return $responseObject;

  }
  
  /**
   * Get Call Log Records by Filter
   *
   * @param `Options` $options Options object
   *
   * @struct Options {
   *     @type int  'account_id'  Internal identifier of a RingCentral account or tilde (~) to indicate the account logged-in within the current session (required)
   *     @type int  'extension_id'  Internal identifier of an extension or tilde (~) to indicate the extension assigned to the account logged-in within the current session (required)
   *     @type string  'extension_number'  Extension number of a user. If specified, returns call log for a particular extension only. Cannot be specified together with the phoneNumber filter (required)
   *     @type string  'phone_number'  Phone number of a caller/call recipient. If specified, returns all calls (both incoming and outcoming) with the mentioned phone number. Cannot be specified together with the extensionNumber filter (required)
   *     @type array[string]  'direction'  The direction for the result records. It is allowed to specify more than one direction. If not specified, both inbound and outbound records are returned. Multiple values are accepted (required)
   *     @type array[string]  'type'  Call type of a record. It is allowed to specify more than one type. If not specified, all call types are returned. Multiple values are accepted (required)
   *     @type array[string]  'view'  The default value is &#39;Simple&#39; for both account and extension call log (required)
   *     @type array[string]  'with_recording'  &#39;True&#39; if only recorded calls have to be returned (required)
   *     @type string  'date_to'  Specifies the ending timestamp for result records. Default: current time (required)
   *     @type string  'date_from'  The start timestamp for result records. Default value is equal to dateTo minus 1 week (required)
   *     @type int  'page'  Indicates the page number to retrieve. Only positive number values are allowed. Default value is &#39;1&#39;. (required)
   *     @type int  'per_page'  Indicates the page size (number of items). If not specified, the value is &#39;100&#39; by default. (required)
   * }
   *
   * @return \RC\client\models\ExtensionCallLogResponse
   */
   //public function accountExtensionCallLogs($account_id, $extension_id, $extension_number, $phone_number, $direction, $type, $view, $with_recording, $date_to, $date_from, $page, $per_page) {
   public function accountExtensionCallLogs($options) {

      if (empty($options)) $options = [];

      
      // verify the required parameter 'account_id' is set
      $this->apiClient->validateParameter($options, 'account_id', 'accountExtensionCallLogs');
      
      // verify the required parameter 'extension_id' is set
      $this->apiClient->validateParameter($options, 'extension_id', 'accountExtensionCallLogs');
      

      // parse inputs
      $resourcePath = "/v1.0/account/{accountId}/extension/{extensionId}/call-log";
      $resourcePath = str_replace("{format}", "json", $resourcePath);
      $method = "GET";
      $httpBody = '';
      $queryParams = array();
      $headerParams = array();
      $formParams = array();

      $_header_accept = $this->apiClient->selectHeaderAccept(array('application/json'));
      if (!is_null($_header_accept)) {
        $headerParams['Accept'] = $_header_accept;
      }
      $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType(array('application/json'));

      $queryParams = $this->apiClient->parseQueryParam($queryParams, $options, 'extension_number', 'extensionNumber');
      $queryParams = $this->apiClient->parseQueryParam($queryParams, $options, 'phone_number', 'phoneNumber');
      $queryParams = $this->apiClient->parseQueryParam($queryParams, $options, 'direction', 'direction');
      $queryParams = $this->apiClient->parseQueryParam($queryParams, $options, 'type', 'type');
      $queryParams = $this->apiClient->parseQueryParam($queryParams, $options, 'view', 'view');
      $queryParams = $this->apiClient->parseQueryParam($queryParams, $options, 'with_recording', 'withRecording');
      $queryParams = $this->apiClient->parseQueryParam($queryParams, $options, 'date_to', 'dateTo');
      $queryParams = $this->apiClient->parseQueryParam($queryParams, $options, 'date_from', 'dateFrom');
      $queryParams = $this->apiClient->parseQueryParam($queryParams, $options, 'page', 'page');
      $queryParams = $this->apiClient->parseQueryParam($queryParams, $options, 'per_page', 'perPage');
      

      

      $resourcePath = $this->apiClient->parsePathParam($resourcePath, $options, 'account_id', 'accountId');
      $resourcePath = $this->apiClient->parsePathParam($resourcePath, $options, 'extension_id', 'extensionId');
      

      

      

      // for model (json/xml)
      if (isset($_tempBody)) {
        $httpBody = $_tempBody; // $_tempBody is the method argument, if present
      } else if (count($formParams) > 0) {
        // for HTTP post (form)
        $httpBody = $formParams;
      }

      // authentication setting, if any
      $authSettings = array();

      // make the API Call
      $response = $this->apiClient->callAPI($resourcePath, $method,
                                            $queryParams, $httpBody,
                                            $headerParams, $authSettings);

      if(! $response) {
        return null;
      }

      $responseObject = $this->apiClient->deserialize($response,'ExtensionCallLogResponse');
      return $responseObject;

  }
  
  /**
   * Get Call Log Record
   *
   * @param `Options` $options Options object
   *
   * @struct Options {
   *     @type int  'account_id'  Internal identifier of a RingCentral account or tilde (~) to indicate the account logged-in within the current session (required)
   *     @type int  'extension_id'  Internal identifier of an extension or tilde (~) to indicate the extension assigned to the account logged-in within the current session (required)
   *     @type int  'call_record_id'  Internal identifier of a call log record (required)
   * }
   *
   * @return \RC\client\models\GetExtensionCallLogRecordResponse
   */
   //public function accountExtensionCallLog($account_id, $extension_id, $call_record_id) {
   public function accountExtensionCallLog($options) {

      if (empty($options)) $options = [];

      
      // verify the required parameter 'account_id' is set
      $this->apiClient->validateParameter($options, 'account_id', 'accountExtensionCallLog');
      
      // verify the required parameter 'extension_id' is set
      $this->apiClient->validateParameter($options, 'extension_id', 'accountExtensionCallLog');
      
      // verify the required parameter 'call_record_id' is set
      $this->apiClient->validateParameter($options, 'call_record_id', 'accountExtensionCallLog');
      

      // parse inputs
      $resourcePath = "/v1.0/account/{accountId}/extension/{extensionId}/call-log/{callRecordId}";
      $resourcePath = str_replace("{format}", "json", $resourcePath);
      $method = "GET";
      $httpBody = '';
      $queryParams = array();
      $headerParams = array();
      $formParams = array();

      $_header_accept = $this->apiClient->selectHeaderAccept(array('application/json'));
      if (!is_null($_header_accept)) {
        $headerParams['Accept'] = $_header_accept;
      }
      $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType(array('application/json'));

      

      

      $resourcePath = $this->apiClient->parsePathParam($resourcePath, $options, 'account_id', 'accountId');
      $resourcePath = $this->apiClient->parsePathParam($resourcePath, $options, 'extension_id', 'extensionId');
      $resourcePath = $this->apiClient->parsePathParam($resourcePath, $options, 'call_record_id', 'callRecordId');
      

      

      

      // for model (json/xml)
      if (isset($_tempBody)) {
        $httpBody = $_tempBody; // $_tempBody is the method argument, if present
      } else if (count($formParams) > 0) {
        // for HTTP post (form)
        $httpBody = $formParams;
      }

      // authentication setting, if any
      $authSettings = array();

      // make the API Call
      $response = $this->apiClient->callAPI($resourcePath, $method,
                                            $queryParams, $httpBody,
                                            $headerParams, $authSettings);

      if(! $response) {
        return null;
      }

      $responseObject = $this->apiClient->deserialize($response,'GetExtensionCallLogRecordResponse');
      return $responseObject;

  }
  
  /**
   * Get Call Recording
   *
   * @param `Options` $options Options object
   *
   * @struct Options {
   *     @type int  'account_id'  Internal identifier of a RingCentral account or tilde (~) to indicate the account logged-in within the current session (required)
   *     @type int  'recording_id'  Internal identifier of recording (returned in Call Log) (required)
   * }
   *
   * @return \RC\client\models\GetCallRecordingResponse
   */
   //public function accountRecording($account_id, $recording_id) {
   public function accountRecording($options) {

      if (empty($options)) $options = [];

      
      // verify the required parameter 'account_id' is set
      $this->apiClient->validateParameter($options, 'account_id', 'accountRecording');
      
      // verify the required parameter 'recording_id' is set
      $this->apiClient->validateParameter($options, 'recording_id', 'accountRecording');
      

      // parse inputs
      $resourcePath = "/v1.0/account/{accountId}/recording/{recordingId}";
      $resourcePath = str_replace("{format}", "json", $resourcePath);
      $method = "GET";
      $httpBody = '';
      $queryParams = array();
      $headerParams = array();
      $formParams = array();

      $_header_accept = $this->apiClient->selectHeaderAccept(array('application/json'));
      if (!is_null($_header_accept)) {
        $headerParams['Accept'] = $_header_accept;
      }
      $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType(array('application/json'));

      

      

      $resourcePath = $this->apiClient->parsePathParam($resourcePath, $options, 'account_id', 'accountId');
      $resourcePath = $this->apiClient->parsePathParam($resourcePath, $options, 'recording_id', 'recordingId');
      

      

      

      // for model (json/xml)
      if (isset($_tempBody)) {
        $httpBody = $_tempBody; // $_tempBody is the method argument, if present
      } else if (count($formParams) > 0) {
        // for HTTP post (form)
        $httpBody = $formParams;
      }

      // authentication setting, if any
      $authSettings = array();

      // make the API Call
      $response = $this->apiClient->callAPI($resourcePath, $method,
                                            $queryParams, $httpBody,
                                            $headerParams, $authSettings);

      if(! $response) {
        return null;
      }

      $responseObject = $this->apiClient->deserialize($response,'GetCallRecordingResponse');
      return $responseObject;

  }
  

}
