<?php
/**
 *  Copyright 2015 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 */

//namespace SwaggerClient;
namespace RC\client;

class DictionaryApi {

  function __construct($apiClient = null) {
    $this->apiClient = $apiClient;
  }

  /**
   * @var ApiClient
   */
  private $apiClient;

  /**
   * get the API client
   */
  public function getApiClient() {
    return $this->apiClient;
  }

  /**
   * set the API client
   */
  public function setApiClient($apiClient) {
    $this->apiClient = $apiClient;
  }

  
  /**
   * Get Country List
   *
   * @param `Options` $options Options object
   *
   * @struct Options {
   *     @type string  'test'  test (required)
   *     @type int  'page'  Indicates the page number to retrieve. Only positive number values are allowed. Default value is &#39;1&#39;. (required)
   *     @type int  'per_page'  Indicates the page size (number of items). If not specified, the value is &#39;100&#39; by default. (required)
   * }
   *
   * @return \RC\client\models\GetCountryListResponse
   */
   //public function dictionaryCountries($test, $page, $per_page) {
   public function dictionaryCountries($options) {

      if (empty($options)) $options = [];

      
      // verify the required parameter 'test' is set
      $this->apiClient->validateParameter($options, 'test', 'dictionaryCountries');
      

      // parse inputs
      $resourcePath = "/v1.0/dictionary/country";
      $resourcePath = str_replace("{format}", "json", $resourcePath);
      $method = "GET";
      $httpBody = '';
      $queryParams = array();
      $headerParams = array();
      $formParams = array();

      $_header_accept = $this->apiClient->selectHeaderAccept(array('application/json'));
      if (!is_null($_header_accept)) {
        $headerParams['Accept'] = $_header_accept;
      }
      $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType(array('application/json'));

      $queryParams = $this->apiClient->parseQueryParam($queryParams, $options, 'page', 'page');
      $queryParams = $this->apiClient->parseQueryParam($queryParams, $options, 'per_page', 'perPage');
      

      

      $resourcePath = $this->apiClient->parsePathParam($resourcePath, $options, 'test', 'test');
      

      

      

      // for model (json/xml)
      if (isset($_tempBody)) {
        $httpBody = $_tempBody; // $_tempBody is the method argument, if present
      } else if (count($formParams) > 0) {
        // for HTTP post (form)
        $httpBody = $formParams;
      }

      // authentication setting, if any
      $authSettings = array();

      // make the API Call
      $response = $this->apiClient->callAPI($resourcePath, $method,
                                            $queryParams, $httpBody,
                                            $headerParams, $authSettings);

      if(! $response) {
        return null;
      }

      $responseObject = $this->apiClient->deserialize($response,'GetCountryListResponse');
      return $responseObject;

  }
  
  /**
   * Get Country
   *
   * @param `Options` $options Options object
   *
   * @struct Options {
   *     @type string  'country_id'  Internal identifier of a country (required)
   * }
   *
   * @return \RC\client\models\CountryInfo
   */
   //public function dictionaryCountry($country_id) {
   public function dictionaryCountry($options) {

      if (empty($options)) $options = [];

      
      // verify the required parameter 'country_id' is set
      $this->apiClient->validateParameter($options, 'country_id', 'dictionaryCountry');
      

      // parse inputs
      $resourcePath = "/v1.0/dictionary/country/{countryId}";
      $resourcePath = str_replace("{format}", "json", $resourcePath);
      $method = "GET";
      $httpBody = '';
      $queryParams = array();
      $headerParams = array();
      $formParams = array();

      $_header_accept = $this->apiClient->selectHeaderAccept(array('application/json'));
      if (!is_null($_header_accept)) {
        $headerParams['Accept'] = $_header_accept;
      }
      $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType(array('application/json'));

      

      

      $resourcePath = $this->apiClient->parsePathParam($resourcePath, $options, 'country_id', 'countryId');
      

      

      

      // for model (json/xml)
      if (isset($_tempBody)) {
        $httpBody = $_tempBody; // $_tempBody is the method argument, if present
      } else if (count($formParams) > 0) {
        // for HTTP post (form)
        $httpBody = $formParams;
      }

      // authentication setting, if any
      $authSettings = array();

      // make the API Call
      $response = $this->apiClient->callAPI($resourcePath, $method,
                                            $queryParams, $httpBody,
                                            $headerParams, $authSettings);

      if(! $response) {
        return null;
      }

      $responseObject = $this->apiClient->deserialize($response,'CountryInfo');
      return $responseObject;

  }
  
  /**
   * Get Language List
   *
   * @param `Options` $options Options object
   *
   * @struct Options {
   * }
   *
   * @return \RC\client\models\
   */
   //public function dictionaryLanguages() {
   public function dictionaryLanguages($options) {

      if (empty($options)) $options = [];

      

      // parse inputs
      $resourcePath = "/v1.0/dictionary/language";
      $resourcePath = str_replace("{format}", "json", $resourcePath);
      $method = "GET";
      $httpBody = '';
      $queryParams = array();
      $headerParams = array();
      $formParams = array();

      $_header_accept = $this->apiClient->selectHeaderAccept(array('application/json'));
      if (!is_null($_header_accept)) {
        $headerParams['Accept'] = $_header_accept;
      }
      $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType(array('application/json'));

      

      

      

      

      

      // for model (json/xml)
      if (isset($_tempBody)) {
        $httpBody = $_tempBody; // $_tempBody is the method argument, if present
      } else if (count($formParams) > 0) {
        // for HTTP post (form)
        $httpBody = $formParams;
      }

      // authentication setting, if any
      $authSettings = array();

      // make the API Call
      $response = $this->apiClient->callAPI($resourcePath, $method,
                                            $queryParams, $httpBody,
                                            $headerParams, $authSettings);

      if(! $response) {
        return null;
      }

      $responseObject = $this->apiClient->deserialize($response,'');
      return $responseObject;

  }
  
  /**
   * Get Language
   *
   * @param `Options` $options Options object
   *
   * @struct Options {
   * }
   *
   * @return \RC\client\models\LanguageInfo
   */
   //public function dictionaryLanguage() {
   public function dictionaryLanguage($options) {

      if (empty($options)) $options = [];

      

      // parse inputs
      $resourcePath = "/v1.0/dictionary/language/{languageId}";
      $resourcePath = str_replace("{format}", "json", $resourcePath);
      $method = "GET";
      $httpBody = '';
      $queryParams = array();
      $headerParams = array();
      $formParams = array();

      $_header_accept = $this->apiClient->selectHeaderAccept(array('application/json'));
      if (!is_null($_header_accept)) {
        $headerParams['Accept'] = $_header_accept;
      }
      $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType(array('application/json'));

      

      

      

      

      

      // for model (json/xml)
      if (isset($_tempBody)) {
        $httpBody = $_tempBody; // $_tempBody is the method argument, if present
      } else if (count($formParams) > 0) {
        // for HTTP post (form)
        $httpBody = $formParams;
      }

      // authentication setting, if any
      $authSettings = array();

      // make the API Call
      $response = $this->apiClient->callAPI($resourcePath, $method,
                                            $queryParams, $httpBody,
                                            $headerParams, $authSettings);

      if(! $response) {
        return null;
      }

      $responseObject = $this->apiClient->deserialize($response,'LanguageInfo');
      return $responseObject;

  }
  
  /**
   * Get Location List
   *
   * @param `Options` $options Options object
   *
   * @struct Options {
   *     @type string  'test'  test (required)
   *     @type array[string]  'order_by'  Sorts results by the specified property. The default value is &#39;City&#39; (required)
   *     @type int  'page'  Indicates the page number to retrieve. Only positive number values are allowed. Default value is &#39;1&#39;. (required)
   *     @type int  'per_page'  Indicates the page size (number of items). If not specified, the value is &#39;100&#39; by default. (required)
   *     @type string  'state_id'  Internal identifier of a state (required)
   * }
   *
   * @return \RC\client\models\GetLocationListResponse
   */
   //public function dictionaryLocations($test, $order_by, $page, $per_page, $state_id) {
   public function dictionaryLocations($options) {

      if (empty($options)) $options = [];

      
      // verify the required parameter 'test' is set
      $this->apiClient->validateParameter($options, 'test', 'dictionaryLocations');
      

      // parse inputs
      $resourcePath = "/v1.0/dictionary/location";
      $resourcePath = str_replace("{format}", "json", $resourcePath);
      $method = "GET";
      $httpBody = '';
      $queryParams = array();
      $headerParams = array();
      $formParams = array();

      $_header_accept = $this->apiClient->selectHeaderAccept(array('application/json'));
      if (!is_null($_header_accept)) {
        $headerParams['Accept'] = $_header_accept;
      }
      $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType(array('application/json'));

      $queryParams = $this->apiClient->parseQueryParam($queryParams, $options, 'order_by', 'orderBy');
      $queryParams = $this->apiClient->parseQueryParam($queryParams, $options, 'page', 'page');
      $queryParams = $this->apiClient->parseQueryParam($queryParams, $options, 'per_page', 'perPage');
      $queryParams = $this->apiClient->parseQueryParam($queryParams, $options, 'state_id', 'stateId');
      

      

      $resourcePath = $this->apiClient->parsePathParam($resourcePath, $options, 'test', 'test');
      

      

      

      // for model (json/xml)
      if (isset($_tempBody)) {
        $httpBody = $_tempBody; // $_tempBody is the method argument, if present
      } else if (count($formParams) > 0) {
        // for HTTP post (form)
        $httpBody = $formParams;
      }

      // authentication setting, if any
      $authSettings = array();

      // make the API Call
      $response = $this->apiClient->callAPI($resourcePath, $method,
                                            $queryParams, $httpBody,
                                            $headerParams, $authSettings);

      if(! $response) {
        return null;
      }

      $responseObject = $this->apiClient->deserialize($response,'GetLocationListResponse');
      return $responseObject;

  }
  

}
