<?php
/**
 *  Copyright 2015 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */

//namespace SwaggerClient\models;
namespace RC\client\models;

use \ArrayAccess;

class BillingPlanInfo implements ArrayAccess {
  static $swaggerTypes = array(
      'id' => 'string',
      'name' => 'string',
      'duration_unit' => 'string',
      'duration' => 'string',
      'type' => 'string'
  );

  static $attributeMap = array(
      'id' => 'id',
      'name' => 'name',
      'duration_unit' => 'durationUnit',
      'duration' => 'duration',
      'type' => 'type'
  );

  
  /**
  * Internal identifier of a billing plan
  * @var string
  */
  public $id;
  /**
  * Billing plan name
  * @var string
  */
  public $name;
  /**
  * Duration period
  * @var string
  */
  public $duration_unit;
  /**
  * Number of duration units
  * @var string
  */
  public $duration;
  /**
  * Billing plan type
  * @var string
  */
  public $type;

  public function __construct(array $data = null) {
    $this->id = $data["id"];
    $this->name = $data["name"];
    $this->duration_unit = $data["duration_unit"];
    $this->duration = $data["duration"];
    $this->type = $data["type"];
  }

  public function offsetExists($offset) {
    return isset($this->$offset);
  }

  public function offsetGet($offset) {
    return $this->$offset;
  }

  public function offsetSet($offset, $value) {
    $this->$offset = $value;
  }

  public function offsetUnset($offset) {
    unset($this->$offset);
  }
}
