<?php
/**
 *  Copyright 2015 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */

//namespace SwaggerClient\models;
namespace RC\client\models;

use \ArrayAccess;

class BrandInfo implements ArrayAccess {
  static $swaggerTypes = array(
      'id' => 'string',
      'name' => 'string',
      'home_country' => 'CountryInfo'
  );

  static $attributeMap = array(
      'id' => 'id',
      'name' => 'name',
      'home_country' => 'homeCountry'
  );

  
  /**
  * Internal identifier of a brand
  * @var string
  */
  public $id;
  /**
  * Brand name, for example  RingCentral UK ,  ClearFax 
  * @var string
  */
  public $name;
  /**
  * Home country information
  * @var CountryInfo
  */
  public $home_country;

  public function __construct(array $data = null) {
    $this->id = $data["id"];
    $this->name = $data["name"];
    $this->home_country = $data["home_country"];
  }

  public function offsetExists($offset) {
    return isset($this->$offset);
  }

  public function offsetGet($offset) {
    return $this->$offset;
  }

  public function offsetSet($offset, $value) {
    $this->$offset = $value;
  }

  public function offsetUnset($offset) {
    unset($this->$offset);
  }
}
