<?php
/**
 *  Copyright 2015 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */

//namespace SwaggerClient\models;
namespace RC\client\models;

use \ArrayAccess;

class ClientProvisioningHintInfo implements ArrayAccess {
  static $swaggerTypes = array(
      'expires_in' => 'int',
      'action_required' => 'boolean'
  );

  static $attributeMap = array(
      'expires_in' => 'expiresIn',
      'action_required' => 'actionRequired'
  );

  
  /**
  * Seconds until expiration date. Returned only if applicable
  * @var int
  */
  public $expires_in;
  /**
  * 'False', if the value of expiresIn is greater than 0 (zero), otherwise - 'True'
  * @var boolean
  */
  public $action_required;

  public function __construct(array $data = null) {
    $this->expires_in = $data["expires_in"];
    $this->action_required = $data["action_required"];
  }

  public function offsetExists($offset) {
    return isset($this->$offset);
  }

  public function offsetGet($offset) {
    return $this->$offset;
  }

  public function offsetSet($offset, $value) {
    $this->$offset = $value;
  }

  public function offsetUnset($offset) {
    unset($this->$offset);
  }
}
