<?php
/**
 *  Copyright 2015 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */

//namespace SwaggerClient\models;
namespace RC\client\models;

use \ArrayAccess;

class ContactInfo implements ArrayAccess {
  static $swaggerTypes = array(
      'first_name' => 'string',
      'last_name' => 'string',
      'company' => 'string',
      'email' => 'string',
      'business_phone' => 'string',
      'business_address' => 'ContactAddressInfo'
  );

  static $attributeMap = array(
      'first_name' => 'firstName',
      'last_name' => 'lastName',
      'company' => 'company',
      'email' => 'email',
      'business_phone' => 'businessPhone',
      'business_address' => 'businessAddress'
  );

  
  /**
  * For User extension type only. Extension user first name
  * @var string
  */
  public $first_name;
  /**
  * For User extension type only. Extension user last name
  * @var string
  */
  public $last_name;
  /**
  * Extension user company name
  * @var string
  */
  public $company;
  /**
  * Email of extension user
  * @var string
  */
  public $email;
  /**
  * Extension user contact phone number
  * @var string
  */
  public $business_phone;
  /**
  * Business address of extension user company
  * @var ContactAddressInfo
  */
  public $business_address;

  public function __construct(array $data = null) {
    $this->first_name = $data["first_name"];
    $this->last_name = $data["last_name"];
    $this->company = $data["company"];
    $this->email = $data["email"];
    $this->business_phone = $data["business_phone"];
    $this->business_address = $data["business_address"];
  }

  public function offsetExists($offset) {
    return isset($this->$offset);
  }

  public function offsetGet($offset) {
    return $this->$offset;
  }

  public function offsetSet($offset, $value) {
    $this->$offset = $value;
  }

  public function offsetUnset($offset) {
    unset($this->$offset);
  }
}
