<?php
/**
 *  Copyright 2015 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */

//namespace SwaggerClient\models;
namespace RC\client\models;

use \ArrayAccess;

class ContactAddressInfo implements ArrayAccess {
  static $swaggerTypes = array(
      'country' => 'string',
      'state' => 'string',
      'city' => 'string',
      'street' => 'string',
      'zip' => 'string'
  );

  static $attributeMap = array(
      'country' => 'country',
      'state' => 'state',
      'city' => 'city',
      'street' => 'street',
      'zip' => 'zip'
  );

  
  /**
  * Country name of extension user company
  * @var string
  */
  public $country;
  /**
  * State/province name of extension user company
  * @var string
  */
  public $state;
  /**
  * City name of extension user company
  * @var string
  */
  public $city;
  /**
  * Street address of extension user company
  * @var string
  */
  public $street;
  /**
  * Zip code of extension user company
  * @var string
  */
  public $zip;

  public function __construct(array $data = null) {
    $this->country = $data["country"];
    $this->state = $data["state"];
    $this->city = $data["city"];
    $this->street = $data["street"];
    $this->zip = $data["zip"];
  }

  public function offsetExists($offset) {
    return isset($this->$offset);
  }

  public function offsetGet($offset) {
    return $this->$offset;
  }

  public function offsetSet($offset, $value) {
    $this->$offset = $value;
  }

  public function offsetUnset($offset) {
    unset($this->$offset);
  }
}
