<?php
/**
 *  Copyright 2015 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */

//namespace SwaggerClient\models;
namespace RC\client\models;

use \ArrayAccess;

class CreateAccountRequest implements ArrayAccess {
  static $swaggerTypes = array(
      'main_number' => 'string',
      'operator' => 'OperatorInfo',
      'service_info' => 'ServiceInfoRequest',
      'status' => 'string',
      'partner_id' => 'string'
  );

  static $attributeMap = array(
      'main_number' => 'mainNumber',
      'operator' => 'operator',
      'service_info' => 'serviceInfo',
      'status' => 'status',
      'partner_id' => 'partnerId'
  );

  
  /**
  * Main account VoIP phone number, either Local or Toll-Free. Cannot be Fax Only. Obtained via lookup/reserve API
  * @var string
  */
  public $main_number;
  /**
  * Operator extension information
  * @var OperatorInfo
  */
  public $operator;
  /**
  * Account service information, brand identifier and service plan
  * @var ServiceInfoRequest
  */
  public $service_info;
  /**
  * The status with which an account is created. The default value is 'Initial'
  * @var string
  */
  public $status;
  /**
  * Partner identifier for this account
  * @var string
  */
  public $partner_id;

  public function __construct(array $data = null) {
    $this->main_number = $data["main_number"];
    $this->operator = $data["operator"];
    $this->service_info = $data["service_info"];
    $this->status = $data["status"];
    $this->partner_id = $data["partner_id"];
  }

  public function offsetExists($offset) {
    return isset($this->$offset);
  }

  public function offsetGet($offset) {
    return $this->$offset;
  }

  public function offsetSet($offset, $value) {
    $this->$offset = $value;
  }

  public function offsetUnset($offset) {
    unset($this->$offset);
  }
}
