<?php
/**
 *  Copyright 2015 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */

//namespace SwaggerClient\models;
namespace RC\client\models;

use \ArrayAccess;

class CustomDataApiResponse implements ArrayAccess {
  static $swaggerTypes = array(
      'id' => 'string',
      'uri' => 'string',
      'value' => 'string',
      'last_modified_time' => 'string',
      'attachment' => 'CustomDataAttachmentInfo'
  );

  static $attributeMap = array(
      'id' => 'id',
      'uri' => 'uri',
      'value' => 'value',
      'last_modified_time' => 'lastModifiedTime',
      'attachment' => 'attachment'
  );

  
  /**
  * Custom data access key
  * @var string
  */
  public $id;
  /**
  * Link to the custom data
  * @var string
  */
  public $uri;
  /**
  * Description of custom data
  * @var string
  */
  public $value;
  /**
  * Time of the last change in custom data
  * @var string
  */
  public $last_modified_time;
  /**
  * Attachment data: link and type
  * @var CustomDataAttachmentInfo
  */
  public $attachment;

  public function __construct(array $data = null) {
    $this->id = $data["id"];
    $this->uri = $data["uri"];
    $this->value = $data["value"];
    $this->last_modified_time = $data["last_modified_time"];
    $this->attachment = $data["attachment"];
  }

  public function offsetExists($offset) {
    return isset($this->$offset);
  }

  public function offsetGet($offset) {
    return $this->$offset;
  }

  public function offsetSet($offset, $value) {
    $this->$offset = $value;
  }

  public function offsetUnset($offset) {
    unset($this->$offset);
  }
}
