<?php
/**
 *  Copyright 2015 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */

//namespace SwaggerClient\models;
namespace RC\client\models;

use \ArrayAccess;

class GetAccountInfoResponse implements ArrayAccess {
  static $swaggerTypes = array(
      'id' => 'string',
      'uri' => 'string',
      'main_number' => 'string',
      'opeartor' => 'GetExtensionInfoResponse',
      'partner_id' => 'string',
      'service_info' => 'ServiceInfoResponse',
      'setup_wizard_state' => 'string',
      'status' => 'string',
      'status_info' => 'AccountStatusInfo'
  );

  static $attributeMap = array(
      'id' => 'id',
      'uri' => 'uri',
      'main_number' => 'mainNumber',
      'opeartor' => 'opeartor',
      'partner_id' => 'partnerId',
      'service_info' => 'serviceInfo',
      'setup_wizard_state' => 'setupWizardState',
      'status' => 'status',
      'status_info' => 'statusInfo'
  );

  
  /**
  * Internal identifier of an account
  * @var string
  */
  public $id;
  /**
  * Canonical URI of an account
  * @var string
  */
  public $uri;
  /**
  * Main phone number of the current account
  * @var string
  */
  public $main_number;
  /**
  * Operator's extension information. This extension will receive all calls and messages intended for the operator
  * @var GetExtensionInfoResponse
  */
  public $opeartor;
  /**
  * Additional account identifier, developed and applied by the client
  * @var string
  */
  public $partner_id;
  /**
  * Account service information, including brand, service plan and billing plan
  * @var ServiceInfoResponse
  */
  public $service_info;
  /**
  * Specifies account configuration wizard state (web service setup). The default value is 'NotStarted'
  * @var string
  */
  public $setup_wizard_state;
  /**
  * Status of the current account
  * @var string
  */
  public $status;
  /**
  * Status information (reason, comment, lifetime). Returned for 'Disabled' status only
  * @var AccountStatusInfo
  */
  public $status_info;

  public function __construct(array $data = null) {
    $this->id = $data["id"];
    $this->uri = $data["uri"];
    $this->main_number = $data["main_number"];
    $this->opeartor = $data["opeartor"];
    $this->partner_id = $data["partner_id"];
    $this->service_info = $data["service_info"];
    $this->setup_wizard_state = $data["setup_wizard_state"];
    $this->status = $data["status"];
    $this->status_info = $data["status_info"];
  }

  public function offsetExists($offset) {
    return isset($this->$offset);
  }

  public function offsetGet($offset) {
    return $this->$offset;
  }

  public function offsetSet($offset, $value) {
    $this->$offset = $value;
  }

  public function offsetUnset($offset) {
    unset($this->$offset);
  }
}
