<?php
/**
 *  Copyright 2015 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */

//namespace SwaggerClient\models;
namespace RC\client\models;

use \ArrayAccess;

class GetVersionResponse implements ArrayAccess {
  static $swaggerTypes = array(
      'uri' => 'string',
      'version_string' => 'string',
      'release_date' => 'string',
      'uri_string' => 'string'
  );

  static $attributeMap = array(
      'uri' => 'uri',
      'version_string' => 'versionString',
      'release_date' => 'releaseDate',
      'uri_string' => 'uriString'
  );

  
  /**
  * Canonical URI of the version info resource
  * @var string
  */
  public $uri;
  /**
  * Version of the RingCentral REST API
  * @var string
  */
  public $version_string;
  /**
  * Release date of this version
  * @var string
  */
  public $release_date;
  /**
  * URI part determining the current version
  * @var string
  */
  public $uri_string;

  public function __construct(array $data = null) {
    $this->uri = $data["uri"];
    $this->version_string = $data["version_string"];
    $this->release_date = $data["release_date"];
    $this->uri_string = $data["uri_string"];
  }

  public function offsetExists($offset) {
    return isset($this->$offset);
  }

  public function offsetGet($offset) {
    return $this->$offset;
  }

  public function offsetSet($offset, $value) {
    $this->$offset = $value;
  }

  public function offsetUnset($offset) {
    unset($this->$offset);
  }
}
