<?php
/**
 *  Copyright 2015 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */

//namespace SwaggerClient\models;
namespace RC\client\models;

use \ArrayAccess;

class MessageAttachmentInfo implements ArrayAccess {
  static $swaggerTypes = array(
      'id' => 'string',
      'uri' => 'string',
      'type' => 'string',
      'content_type' => 'string',
      'vm_duration' => 'int'
  );

  static $attributeMap = array(
      'id' => 'id',
      'uri' => 'uri',
      'type' => 'type',
      'content_type' => 'contentType',
      'vm_duration' => 'vmDuration'
  );

  
  /**
  * Internal identifier of a message attachment
  * @var string
  */
  public $id;
  /**
  * Canonical URI of a message attachment
  * @var string
  */
  public $uri;
  /**
  * Type of message attachment
  * @var string
  */
  public $type;
  /**
  * MIME type for a given attachment, for instance 'audio/wav'
  * @var string
  */
  public $content_type;
  /**
  * Voicemail only Duration of the voicemail in seconds
  * @var int
  */
  public $vm_duration;

  public function __construct(array $data = null) {
    $this->id = $data["id"];
    $this->uri = $data["uri"];
    $this->type = $data["type"];
    $this->content_type = $data["content_type"];
    $this->vm_duration = $data["vm_duration"];
  }

  public function offsetExists($offset) {
    return isset($this->$offset);
  }

  public function offsetGet($offset) {
    return $this->$offset;
  }

  public function offsetSet($offset, $value) {
    $this->$offset = $value;
  }

  public function offsetUnset($offset) {
    unset($this->$offset);
  }
}
