<?php
/**
 *  Copyright 2015 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */

//namespace SwaggerClient\models;
namespace RC\client\models;

use \ArrayAccess;

class RecordingInfo implements ArrayAccess {
  static $swaggerTypes = array(
      'id' => 'int',
      'uri' => 'string',
      'type' => 'string',
      'content_uri' => 'string'
  );

  static $attributeMap = array(
      'id' => 'id',
      'uri' => 'uri',
      'type' => 'type',
      'content_uri' => 'contentUri'
  );

  
  /**
  * Internal identifier of the call recording
  * @var int
  */
  public $id;
  /**
  * Link to the call recording metadata resource
  * @var string
  */
  public $uri;
  /**
  * Indicates recording mode used
  * @var string
  */
  public $type;
  /**
  * Link to the call recording binary content
  * @var string
  */
  public $content_uri;

  public function __construct(array $data = null) {
    $this->id = $data["id"];
    $this->uri = $data["uri"];
    $this->type = $data["type"];
    $this->content_uri = $data["content_uri"];
  }

  public function offsetExists($offset) {
    return isset($this->$offset);
  }

  public function offsetGet($offset) {
    return $this->$offset;
  }

  public function offsetSet($offset, $value) {
    $this->$offset = $value;
  }

  public function offsetUnset($offset) {
    unset($this->$offset);
  }
}
