<?php
/**
 *  Copyright 2015 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */

//namespace SwaggerClient\models;
namespace RC\client\models;

use \ArrayAccess;

class ServiceInfoResponse implements ArrayAccess {
  static $swaggerTypes = array(
      'uri' => 'string',
      'billing_plan' => 'BillingPlanInfo',
      'brand' => 'BrandInfo',
      'service_plan' => 'ServicePlanInfo',
      'target_service_plan' => 'TragetServicePlanInfo'
  );

  static $attributeMap = array(
      'uri' => 'uri',
      'billing_plan' => 'billingPlan',
      'brand' => 'brand',
      'service_plan' => 'servicePlan',
      'target_service_plan' => 'targetServicePlan'
  );

  
  /**
  * Canonical URI of a service info resource
  * @var string
  */
  public $uri;
  /**
  * Information on account billing plan
  * @var BillingPlanInfo
  */
  public $billing_plan;
  /**
  * Information on account brand
  * @var BrandInfo
  */
  public $brand;
  /**
  * Information on account service plan
  * @var ServicePlanInfo
  */
  public $service_plan;
  /**
  * Information on account target service plan
  * @var TragetServicePlanInfo
  */
  public $target_service_plan;

  public function __construct(array $data = null) {
    $this->uri = $data["uri"];
    $this->billing_plan = $data["billing_plan"];
    $this->brand = $data["brand"];
    $this->service_plan = $data["service_plan"];
    $this->target_service_plan = $data["target_service_plan"];
  }

  public function offsetExists($offset) {
    return isset($this->$offset);
  }

  public function offsetGet($offset) {
    return $this->$offset;
  }

  public function offsetSet($offset, $value) {
    $this->$offset = $value;
  }

  public function offsetUnset($offset) {
    unset($this->$offset);
  }
}
